name: Full Test Suite

# Run all tests together
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Monday at 8 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  api-tests:
    name: API Tests
    uses: ./.github/workflows/api-tests.yml
  
  web-tests:
    name: Web Tests
    uses: ./.github/workflows/web-tests.yml
    needs: api-tests
  
  performance-tests:
    name: Performance Tests
    uses: ./.github/workflows/performance-tests.yml
    needs: [api-tests, web-tests]
  
  test-summary:
    name: Generate Test Summary
    runs-on: ubuntu-latest
    needs: [api-tests, web-tests, performance-tests]
    if: always()
    
    steps:
    - name: Create Summary Report
      run: |
        echo "# 🎯 QA Portfolio - Test Suite Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Test Results Overview" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Test Type | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| API Tests | ${{ needs.api-tests.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Web Tests | ${{ needs.web-tests.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Performance Tests | ${{ needs.performance-tests.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
